### ISSUE TITLE
Use in React Native Mobile app

### ISSUE THREAD

**Issue by kirtishjain** [shime/dominant-color#4]
Hi, 
I want to use your code in react native (0.54) mobile application for both platform i.e. iOS and Android.
Can I use it and if YES then please provide me an example how to integrate and use it.

Thanks in advance.
Best Regards
Kirtish

**Comment by kirtishjain** [comment]
Hi Hrvoje,

Please reply. I would require it in emergency for one of my React Native project.

Thanks in advance

**Comment by shime** [comment]
Sorry, but I don't have any experience with React Native. This project depends on imagemagick and I don't know if it's possible to make it available on mobile platforms. 

I think your biggest problem is getting imagemagick to work on mobile, but again, I don't have any experience with that so I'm just taking a guess here.

**Comment by kirtishjain** [comment]
Thanks for your prompt response.

No issues.
